### ISSUE TITLE
There is no symmetric_focal_tversky_loss in loss_functions.py

### ISSUE THREAD

**Issue by oikosohn** [mlyg/unified-focal-loss#6]
I think `symmetric_focal_tversky_loss` needs to be partially changed from the code of the `asymmetric_focal_tversky_loss` 

```python
# asymmetric_focal_tversky_loss 
...
back_dice = (1-dice_class[:,0]) 
fore_dice = (1-dice_class[:,1]) * K.pow(1-dice_class[:,1], -gamma)

# symmetric_focal_tversky_loss 
...
back_dice = (1-dice_class[:,0]) * K.pow(1-dice_class[:,0], -gamma)
fore_dice = (1-dice_class[:,1]) * K.pow(1-dice_class[:,1], -gamma)
```

Is this right?

If I am wrong, can you tell me when it will be updated?

**Comment by mlyg** [comment]
Thanks again for spotting this! It is exactly as you would have suspected. I have added this loss function to the file.
