### ISSUE TITLE
Integration into MIScnn

### ISSUE THREAD

**Issue by muellerdo** [mlyg/unified-focal-loss#7]
Hello @mlyg / Yeung et al.,

thank you for this great and really interesting work! :-)
Also, the implementation code and the manuscript are both really well written. 

I just wanted to ask if we can/are allowed to integrate your metric implementations into MIScnn?
Of course with a reference to this repository as well as your manuscript.

Cheers,
Dominik Müller

**Comment by mlyg** [comment]
Hi Dominik,

Many thanks for your interest! I am very grateful for your excellent work creating the MIScnn pipeline - I have been using it extensively for many of my projects.

Absolutely feel free to integrate these loss functions into the framework.

Best wishes,
Michael

**Comment by muellerdo** [comment]
Hey Michael,

very glad to hear that MIScnn is useful for your research!

Check out this pull request: https://github.com/frankkramer-lab/MIScnn/pull/108
If you don't have any concerns with it, I'm going to push it to our dev branch soon.

Cheers,
Dominik

**Comment by mlyg** [comment]
Hi Dominik,

I had a look over the pull request - looks great, no issues from my end!

Best wishes,
Michael

**Comment by muellerdo** [comment]
Hey Michael,

the new loss functions are now live in MIScnn 1.3.0 :)
Thanks for everything!

Cheers,
Dominik
